APP_ABI := armeabi-v7a x86
APP_PLATFORM := android-15
APP_STL := gnustl_shared
APP_MODULES := libjpeg libtiff libpng MagickCore-7 MagickWand-7
NDK_TOOLCHAIN_VERSION := clang

APP_CFLAGS += \
    -DMAGICKCORE_HDRI_ENABLE=0 \
    -DMAGICKCORE_QUANTUM_DEPTH=8 \

APP_CPPFLAGS += \
    -DMAGICKCORE_HDRI_ENABLE=0 \
    -DMAGICKCORE_QUANTUM_DEPTH=8 \
